@base=https://localhost:5001
### Retrieves a provider by it's id
GET {{base}}/providers/5
Accept: application/json

### Import a list of providers
POST {{base}}/providers/import
Content-Type: application/json

[
  {
    "provider_id": 1,
    "name": "Alex",
    "postal_address" : "2 rue des invalides, Paris",
    "created_at": "2022-01-30T12:21:26Z",
    "type" : "rental"
  },
  {
    "provider_id":2,
    "name": "Mike",
    "postal_address" : "1 rue de la paix, Paris",
    "created_at": "2023-01-30T12:21:26Z",
    "type" : "vfh"
  }
]